/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloTransfer */

#ifndef _Included_HelloTransfer
#define _Included_HelloTransfer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloTransfer
 * Method:    helloTransfer
 * Signature: (ZIJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_HelloTransfer_helloTransfer
  (JNIEnv *, jclass, jboolean, jint, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
